# Generated by Django 2.1.7 on 2020-08-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.CharField(default=11111111, max_length=8),
            preserve_default=False,
        ),
    ]
