# Generated by Django 2.1.7 on 2020-08-29 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_userinfo_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendinfo',
            old_name='friend_id',
            new_name='friendId',
        ),
        migrations.RenameField(
            model_name='friendinfo',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='profile_image_url',
            new_name='profileImageUrl',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='wish_list_url',
            new_name='wishListUrl',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='userName',
        )
    ]
