# Generated by Django 2.1.7 on 2020-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20200829_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='birthday',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday_day',
            field=models.CharField(default=15, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday_month',
            field=models.CharField(default=12, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday_year',
            field=models.CharField(default=1994, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
