name: tampre
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  badges: ^1.1.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  cupertino_icons: ^0.1.3
  provider: ^4.3.2
  flutter_calendar_carousel: ^1.4.12
  fluttertoast: ^7.0.2
  intl: ^0.16.1
  url_launcher: ^3.0.3
  quartet: ^0.1.1
  image_picker: ^0.6.7+7
  http: ^0.12.0
  flutter_dotenv: ^2.1.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - json/
    - .env

flutter_native_splash:
  image: "images/gift.png" 
  color: "ffb6c1"
