version: "3"

services:
  db:
    container_name: django_db
    image: postgres:11.2
    volumes:
      - django_data_volume:/var/lib/postgresql/data
  rest_api:
    container_name: django_rest_api
    build:
      context: .
      dockerfile: DockerfilePython
    volumes:
      - ./django_rest_api:/django_rest_api
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  django_data_volume: