swagger: "2.0"
info:
  description: "TAMPRE用のAPI"
  version: "1.0.0"
  title: "TAMPRE"
host: "tampre"
basePath: "/v1"
tags:
- name: "user"
  description: "user情報管理"
- name: "friends"
  description: "friends管理"
schemes:
- "https"
paths:
  /user:
    post:
      tags:
      - "user"
      summary: "User情報の登録"
      description: "User情報を登録する"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "query"
        description: "ユーザID"
        required: true
        type: "string"
      - name: "user_name"
        in: "query"
        description: "ユーザ名"
        required: true
        type: "string"
      - name: "birthday"
        in: "query"
        description: "誕生日"
        required: true
        type: "string"
        format: "date"
        pattern: "YYYY-MM-DD"
        minLength: 0
        maxLength: 10
      - name: "profile_image_url"
        in: "query"
        description: "プロフ画像のURL"
        required: true
        type: "string"
        format: "url"
      - name: "wish_list_url"
        in: "query"
        description: "欲しいものリストのURL"
        required: true
        type: "string"
        format: "url"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid value"
  /user/{user_id}:
    get:
      tags:
      - "user"
      summary: "User情報の取得"
      description: "User情報を取得する"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "user_id"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid value"
    put:
      tags:
      - "user"
      summary: "User情報の更新"
      description: "User情報を更新する"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "user_id"
        required: true
        type: "string"
      - name: "user_name"
        in: "query"
        description: "ユーザ名"
        type: "string"
      - name: "birthday"
        in: "query"
        description: "誕生日"
        type: "string"
        format: "date"
        pattern: "YYYY-MM-DD"
        minLength: 0
        maxLength: 10
      - name: "profile_image_url"
        in: "query"
        description: "プロフ画像のURL"
        type: "string"
        format: "url"
      - name: "wish_list_url"
        in: "query"
        description: "欲しいものリストのURL"
        type: "string"
        format: "url"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid value"
    delete:
      tags:
      - "user"
      summary: "User情報の削除"
      description: "User情報を削除する"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "user_id"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid value"
  /friends/{user_id}:
    get:
      tags:
      - "friends"
      summary: "friend情報のリストを取得"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "user_id"
        required: true
        type: "string"
      responses:
        "200":
          description: "get friend info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        "404":
          description: "No Data"
  /friends/{user_id}/{friend_id}:
    delete:
      tags:
      - "friends"
      summary: "友達を削除する"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "user_id"
        required: true
        type: "string"
      - name: "friend_id"
        in: "path"
        description: "friend_id"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid request"
  /friends/request/{user_id}/{friend_id}:
    post:
      tags:
      - "friends"
      summary: "友達申請を送る"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "user_id"
        required: true
        type: "string"
      - name: "friend_id"
        in: "path"
        description: "friend_id"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid request"
  /friends/requested/{user_id}:
    get:
      tags:
      - "friends"
      summary: "自分に来ている友達申請のリストを取得"
      description: "毎回、アプリ起動時に呼び出し、友達申請が来ていればその情報を取得する。なければ空のリストを返す"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "user_id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "List of user object"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
  /friends/requested/{user_id}/{friend_id}:
    post:
      tags:
      - "friends"
      summary: "自分に来ている友達申請に返答する"
      description: "trueで許可、falseで拒否"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "user_id"
        type: "string"
        required: true
      - in: "path"
        name: "friend_id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "List of user object"
        required: true
        schema:
          type: "object"
          properties:
            accept:
              type: "boolean"
      responses:
        "200":
          description: "successful operation"
  
definitions:
  User:
    type: "object"
    properties:
      user_id:
        type: "string"
      user_name:
        type: "string"
      birthday:
          type: "integer"
          format: "int64"
      wish_list_url:
        type: "string"
        format: "url"
      user_image_url:
          type: "string"
          format: "url"